# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #          name: Chmod permissions # if permission for Gradlew Dependencies fail, use this.
      #          command: sudo chmod +x ./gradlew
      - run:
          name: Decode Google and Play Store Services Json
          command: |
            echo $GOOGLE_SERVICE_JSON | base64 -d > app/google-services.json
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run App Module Unit Tests
          command: ./gradlew :app:testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Run Domain Module Unit Tests
          command: ./gradlew :domain:test
      - store_artifacts:
          path: domain/build/reports
      - store_test_results:
          path: domain/build/test-results
      - run:
          name: Run Data Module Unit Tests
          command: ./gradlew :data:testDebugUnitTest
      - store_artifacts:
          path: data/build/reports
      - store_test_results:
          path: data/build/test-results
      - run:
          name: Run Lint Test
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports

  deploy-prod:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Decode Google and Play Store Services Json
          command: |
            echo $GOOGLE_SERVICE_JSON | base64 -d > app/google-services.json
            echo $PLAYSTORE_SERVICE_JSON | base64 -d > app/chow-play-services.json
            echo $KEY_STORE_JKS | base64 -d > app/chow_key_store.jks
      - run:
          name: Approve SDK Licenses
          # Captures SIGPIPE 141 error but still allow repeating "y" to accept all licenses
          command: yes | sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - run:
          name: Assemble Bundles
          command: ./gradlew clean bundleRelease
      - run:
          name: Publish Application Bundle to Play Store
          command: ./gradlew publishReleaseBundle

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feat-.*/
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master # List of branches for CI to build. { - /feature-.*/ to use regex }